### ISSUE TITLE
[Issue]: Error "Failed to write! (-11)" when copying save to memory card.

### ISSUE THREAD

**Issue by Jdbaii** [emukidid/swiss-gc#803] opened 2023-04-19 23:12 UTC
### Describe the bug

Backing up saves (copying them from the memory card to the SD card) works no issues, when restoring them it gives the error:
Failed to write! (-11)
carda:/save.gci

The save appears on the memory card though, and when I launch the game, the save is there.
But frequently when a restore is attempted, the console crashes with an Exception (DSI) occurred, sometimes immediately, sometimes on the second or third save copied in a row.

It's odd that the save seems to be copied perfectly fine and yet it throws an error. Presumably, the error is preventing it from freeing up memory and that leads to the DSI Exception when it runs out of memory, but I don't really know.

I use an official 1019 block memory card, and the latest version of Swiss (downloaded just earlier today)

### Steps to reproduce

- Copy a save to SD
- Delete the save from the memory card
- Copy the save back to the memory card
- Error occurs
- Look at memory card in the file browser, the save seems to be there.
- Launch game, save works perfectly fine.
- But... Restore multiple saves in a row, and the console crashes with Exception (DSI) occurred

### Expected behavior

I'd expect there to be no crashes or errors.

### Add screenshots

![P_20230420_010826_1_1](https://user-images.githubusercontent.com/1253406/233218948-102f5dc9-6f2e-4440-88cf-75443ede136c.jpg)

**Comment by Extrems** [comment] 2023-04-19 23:47
Duplicate of issue #698.

**Closed by Extrems** 2023-04-19 23:47 UTC
Labels: duplicate
