### ISSUE TITLE
[Issue]: Batman: Vengeance (NTSC-U) not loading through GC Loader

### ISSUE THREAD

**Issue by joaquincoelho** [emukidid/swiss-gc#732] opened 2022-09-17 14:08 UTC
### Describe the bug

Batman Vengeance is not working when trying to load it from the GC Loader, all I get is a blank screen.

*Swiss version: v0.6r1362
*DOL MD5: F54FD223EC22DEF35FE06A0ED4A7CAD9

A similar issue (but through SD2SP2 instead of GC Loader) was previously reported as issue #307 and fixed.

Thanks.

### Steps to reproduce

Load the game through GC Loader

### Expected behavior

Regular game load

**Comment by Extrems** [comment] 2022-09-17 15:42
Cannot reproduce.

**Comment by joaquincoelho** [comment] 2022-09-25 09:00
For the record, disabling "emulate read speed" made the game run fine.

**Comment by ScytheandGenesisGames** [comment] 2022-10-01 18:48
My copy of Batman Vengeance runs well without any issue mine is set as 32 MHZ for speed

**Comment by Wiggo32** [comment] 2022-11-30 17:51
To add to this (if related)... Batman Vengence loads ok but hangs after memory card selection. The last known revision that worked fine was [Swiss v0.6r1318](https://github.com/emukidid/swiss-gc/releases/tag/v0.6r1318). All subsequent revisions past that one caused the crashing issue after either reading the memory card or continuing without a memory card.

**Comment by kwigbo** [comment] 2022-12-16 20:53
I get a crash after the intro animation after start game. 😞

**Comment by Extrems** [comment] 2022-12-16 21:13
> I get a crash after the intro animation after start game. 😞
> 
> Swiss v0.6r1387

I cannot reproduce this issue. Do you have any weird settings enabled?

**Comment by Wiggo32** [comment] 2022-12-17 20:14
Default settings. I have 4 modded Gamecubes of different varieties (including JPN) and they all crash with newer versions of Swiss. I have been testing by running the game without a memory card and leaving the memory card emulation option default OFF. With Swiss v0.6r1318 the game runs fine on default settings.

**Comment by acefondu** [comment] 2023-03-02 14:09
I am having a very similar issue. I get to the screen to pick a memory card, make a save, then it brings me to the title screen where it's supposed to show menu options but they never show up and the game hangs. Have to power off to reboot. I'm using the latest version v0.6r1420 with no strange settings applied.

**Comment by Extrems** [comment] 2023-08-06 20:54
Fixed in 70b3193 (r1526).

**Closed by Extrems** 2023-08-06 20:54 UTC
Labels: bug, hypervisor, read speed
