### ISSUE TITLE
Eternal Darkness freeze on Poem

### ISSUE THREAD

**Issue by Bakuku** [emukidid/swiss-gc#366] opened 2020-07-15 17:08 UTC
With the latest build of SWISS v0.5r856 Eternal Darkness refuses to boot when selecting Progressive or Interlaced image on the Edgar Allen Poe poem screen.

Game was last confirmed working on r827 I believe before updating to latest r856.

Games running off of SD-card from the Wiikey/Wasp Fusion.

**Comment by Extrems** [comment] 2020-07-15 18:27
Cannot reproduce using an SD Card Adapter, but can reproduce using the File Service Protocol (no streaming audio emulation).

**Comment by Bakuku** [comment] 2020-07-15 21:18
Meaning?

**Comment by Extrems** [comment] 2020-07-15 22:02
The game is stuck because the track isn't progressing to completion, as streaming audio isn't currently emulated with the Wiikey Fusion.

**Comment by Extrems** [comment] 2020-07-19 23:45
Fixed in 48d80be (r861) for Wiikey Fusion.

**Comment by Bakuku** [comment] 2020-08-01 00:33
Game has static during Poem and hangs after static Poem sequence.

SWISS: r867 on Wiikey Fusion

**Comment by Extrems** [comment] 2020-08-01 01:03
Verify your disc image match Redump.

**Comment by Bakuku** [comment] 2020-08-01 16:16
I checked and they match.

**Comment by Extrems** [comment] 2020-08-01 16:52
I don't know what to tell you. It's working perfectly fine as far as I'm able to test it without a Wiikey Fusion.

Is the file fragmented?

**Comment by Extrems** [comment] 2020-08-01 16:59
And are you checking the disc image **on** the Wiikey Fusion's SD card, or the original copy on your PC?
If the latter, are you doing something funny like using a disc shrinking tool other than NKit? Your symptoms sound very much like broken file alignment.

**Comment by Bakuku** [comment] 2020-08-01 19:06
As far as I know the file is not fragmented. 
No shrinking tool is used. 
Check is done from copy on harddrive. 

Might have to double check pin 28. If I recall correctly, it is not connected from Wkf to GC using the QSB from Citrus3000psi. 

If I were to connect it would this not result in signal conflict with the DVD drive having the Wkf is passthrough mode (DVD drive behind Wkf to retain its functionality)?

**Comment by Bakuku** [comment] 2020-08-02 03:24
I replaced the internal battery inside the Gamecube as it was empty and nog keeping time anymore and the game now Boots properly with the Poem recited and in game music (atmosphere) playing.

I don’t know if the battery was the issue or if SWISS is depended on it.

**Comment by Extrems** [comment] 2020-08-02 03:36
This is not my first time hearing about problems with a flat battery, and I'm _really_ puzzled as to what malfunctions it's causing.

**Closed** 2022-03-03 21:05 UTC
Labels: bug, hypervisor, streaming audio
