### ISSUE TITLE
Compatible GameCube controller not working with some games

### ISSUE THREAD

**Issue by rapperskull** [emukidid/swiss-gc#447] opened 2021-01-11 19:05 UTC
Hi. I load games from an SD card in the SD2SP2 adapter. Today I received a compatible GameCube controller from China, pretty much a clone of the original one, but I found out a strange bug. It works with Swiss, but not with some games. When I launch the affacted games no input is detected, not even the reboot combo. I tested Crash Tag Team Racing and The Simpsons Hit & Run and it doesn't work, while Animal Crossing detects it fine. All games are PAL. I would also like to point out that I have two other third party controllers (from different brands) and they all work fine. Swiss version is r994. I don't understand why something like that would happen. I'm not even sure there's a way to detect the controller brand or model.
Thank you in advance for your help.

**Comment by Extrems** [comment] 2021-01-11 19:46
Duplicate of issue #428.

**Closed by Extrems** 2021-01-11 19:46 UTC
Labels: duplicate
