### ISSUE TITLE
Swiss will not load all disc images “Disc does not contain valid word at 0x1C”

### ISSUE THREAD

**Issue by travazz** [emukidid/swiss-gc#363] opened 2020-07-10 17:00 UTC
I’ve uploaded pictures below. Swiss will not load all disc images when it powers on. When I change the name to boot, the non loading images load automatically and start playing without a problem. I know the images I ripped are working, what could be causing this problem?

![6878227A-710A-43C7-8F8E-1E37E8174866](https://user-images.githubusercontent.com/68122147/87179569-f80d3500-c2ac-11ea-9710-c736faecd94d.jpeg)
![EB6F7B6C-A5EB-4E96-AA97-55076910D378](https://user-images.githubusercontent.com/68122147/87179577-fc395280-c2ac-11ea-84af-0dad22e0cf70.jpeg)
![5D099916-2608-4695-9F58-269689E0CA3D](https://user-images.githubusercontent.com/68122147/87179584-fcd1e900-c2ac-11ea-9c66-92048882b8fe.jpeg)
![6AA58062-2E80-415C-859C-A647AB404FD6](https://user-images.githubusercontent.com/68122147/87179588-fe031600-c2ac-11ea-9174-baf261995cdf.jpeg)

**Comment by Extrems** [comment] 2020-07-10 17:05
Duplicate of issue #342.

**Closed by Extrems** 2020-07-10 17:05 UTC

**Comment by travazz** [comment] 2020-07-10 18:51
Updating to 1.01 didn’t fix the problem and my battery is new
