### ISSUE TITLE
Swiss wont load the pokemon Colosseum bonus disc and sonic gems collection

### ISSUE THREAD

**Issue by EzioisAwesome56** [emukidid/swiss-gc#158] opened 2017-03-23 02:15 UTC
When trying to boot the pokemon Colosseum bonus disc, it stuck at a black screen and when trying to load a game on sonic gems it gives a disc read error

**Comment by emukidid** [comment] 2018-12-12 06:44
Duplicate of Issue #190

**Closed by emukidid** 2018-12-12 06:44 UTC
