### ISSUE TITLE
GUN and Finding Nemo don't work

### ISSUE THREAD

**Issue by pacmaster2002** [emukidid/swiss-gc#511] opened 2021-03-25 02:43 UTC
When I try to load Finding Nemo or GUN on Swiss, both do not start and end up resetting my GameCube. With GUN it will just automatically reboot and go back into swiss, whereas Finding Nemo will get through the intro FMV'S right before the main menu screen, will crash and reset my GameCube back into swiss. Will there be any fix to this?

**Comment by Extrems** [comment] 2021-03-25 03:27
Duplicate of issues #494 and #500.

**Closed by Extrems** 2021-03-25 03:27 UTC
Labels: duplicate
