### ISSUE TITLE
Time and Date in Swiss not working when booting via ViperGC Extreme

### ISSUE THREAD

**Issue by antmerino** [emukidid/swiss-gc#530] opened 2021-05-13 10:50 UTC
In the last version, the Date and Time, Swiss resets to 2001 at 0:0:00, but in the system calendar it's in teh current days. It's as if the swiss didn't show the real time.

**Comment by antmerino** [comment] 2021-05-13 21:13
I forgot it, I have a viper extreme with swiss put in plugin store

**Comment by emukidid** [comment] 2021-05-13 22:31
>It's as if the swiss didn't show the real time.

What it really is, is "it's as if the ViperGC Extreme is a strange piece of hardware that gets in the way of Swiss reading the time".

**Comment by Extrems** [comment] 2021-05-13 22:36
Duplicate of issue #141.

**Closed by Extrems** 2021-05-13 22:36 UTC
Labels: duplicate

**Comment by antmerino** [comment] 2021-05-13 22:52
Sorry , don't have any solution? Any advice? Thanks a lot for your work
