### ISSUE TITLE
F-Zero GX Resetting

### ISSUE THREAD

**Issue by KongsNutz** [emukidid/swiss-gc#727] opened 2022-09-06 03:56 UTC
F-Zero GX will randomly reset the game back to the Sega Logo.
It doesn't seem to happen anywhere in particular.

Swiss Version - 1362
ISOType - Verified nkit.iso
Region - NTSC on PAL GC
Boot method - PicoBoot + SDGecko 
Video Forced - None
Memcard Emulation - Yes

**Comment by Extrems** [comment] 2022-09-06 04:19
Duplicate of issue #401.

**Closed by Extrems** 2022-09-06 04:19 UTC
Labels: duplicate
