### ISSUE TITLE
Star Fox Adventures Not Booting

### ISSUE THREAD

**Issue by 9NateDawggg7** [emukidid/swiss-gc#492] opened 2021-03-04 18:35 UTC
As the title states, I've been trying to play Star Fox Adventures to no avail. When I click to boot the game, it says "booting DOL" then just goes to a black screen and doesn't do anything. I'm using the GC Loader PNP with a 128gb Sandisk SD and a standard memory card for storage. Currently still using v0.5r1026 but have already downloaded v0.5r1047 to my computer. Are there any particular setting I need to enable, or has this perhaps been fixed in the newest update?

**Comment by Extrems** [comment] 2021-03-04 18:48
Duplicate of issue #475.

**Closed by Extrems** 2021-03-04 18:48 UTC
Labels: duplicate
