### ISSUE TITLE
[Issue]: Star wars: The clone wars, does not work correctly.

### ISSUE THREAD

**Issue by FascistMan** [emukidid/swiss-gc#776] opened 2023-02-02 00:44 UTC
### Describe the bug

The game starts normally, but at the moment of going to the second mission the game freezes and when trying to start a multiplayer game the console restarts.

### Steps to reproduce

I start the game normally from my micro sd Sandisk Ultra 256GB on my SD2SP2, the first mission is played normally, but when I press the "continue" or "next mission" button the game freezes.
And not to mention the multiplayer that makes the entire console completely restart,

### Expected behavior

Well, I would like at least the main campaign to be completely playable and it's a shame because it was precisely because of this game that I installed Swiss on my Gamecube ;(

**Comment by Extrems** [comment] 2023-03-01 03:46
Duplicate of issue #433.

**Closed by Extrems** 2023-03-01 03:46 UTC
Labels: duplicate
