### ISSUE TITLE
[Issue]: Emulated Memory Card not working

### ISSUE THREAD

**Issue by RobotLimeLtd** [emukidid/swiss-gc#730] opened 2022-09-09 20:03 UTC
### Describe the bug

On a fresh install of Swiss (r1362), I enabled "emulate memory card" and no other settings.  On the same card, my game images are all ISOs of USA Gamecube games.  The card (128GB SanDisk SD card, loaded via Picoboot/sd2sp2) is formatted as FAT 32.

I loaded Metroid Prime (which prompted me to format the card on first use) which was able to see and use the emulated memory card(s).  This game continues to see the memory card(s) on subsequent reloads, however many games will not recognise the memory card at all.

Games that cannot see the emulated memory card(s): 1080 Avalanche, Eternal Darkness, Crazy Taxi.

Games that can see and use the memory card(s):  Metroid Prime, Luigi's Mansion, Rogue Leader, Super Mario Sunshine

### Steps to reproduce

Fresh install of Swiss r1362, enable emulated memory card in settings, then launch Metroid Prime (v1.02 USA ISO).

Format the memory card when prompted (while attempting to created first game save).

Quit Metroid Prime and launch 1080 Avalanche (USA ISO), Eternal Darkness or Crazy Taxi.

### Expected behavior

All games loaded from ISO should be able to detect and use the emulated memory card; however some games (mentioned above do not recognise a memory card as present.

**Comment by Extrems** [comment] 2022-09-09 20:14
Duplicate of issue #493.

**Closed by Extrems** 2022-09-09 20:14 UTC
Labels: duplicate
