### ISSUE TITLE
[Issue]: Retrobit LegacyGC controller not working in swiss menu

### ISSUE THREAD

**Issue by Hareluya79** [emukidid/swiss-gc#860] opened 2024-03-28 17:02 UTC
### Describe the bug

only UP direction is working, down left right not working in menu but works fine when loaded in game.

### Steps to reproduce

just plug in a legacygc controller 

### Expected behavior

only UP is working

**Comment by Extrems** [comment] 2024-03-28 17:08
Duplicate of issue #428.

**Closed by Extrems** 2024-03-28 17:08 UTC
Labels: duplicate
