### ISSUE TITLE
Feature request: Boot straight into another .iso-file

### ISSUE THREAD

**Issue by sandbuffelN** [emukidid/swiss-gc#373] opened 2020-08-04 18:48 UTC
**Short story:**

A way to just bypass the region lock booting straight into any region game on any region console.

**Long story:**

Would love to be able to put a boot.iso-file of Swiss, but instead of getting into the Swiss software booting straight into another .iso-file (for example game.iso).

Background to this is that I bought a GC Loader thinking it would allow me to directly load NTSC-U games just as when loading up a genuine disc in my Spice Orange and Symphonic Green consoles, popping the SD-cards into individual NDS-cases to preserve my collection and being able to play it on my favorite variants of the Gamecube.

**Comment by Extrems** [comment] 2020-08-04 20:13
Duplicate of issue #259.

**Closed by Extrems** 2020-08-04 20:13 UTC
