### ISSUE TITLE
[Issue]: Exception occurs when trying to open Cheats menu on a physical disc DOL

### ISSUE THREAD

**Issue by AnthonyRyuki** [emukidid/swiss-gc#686] opened 2022-06-04 21:00 UTC
### Describe the bug

When trying to open the cheats menu after selecting a DOL inside a physical disc, an exception will occur and Swiss will crash, displaying an exception handler. This does not happen when trying to use cheats on ISOs.

### Steps to reproduce

-Select the inserted game disc as the media you want to explore.
-Highlight the game's DOL and press A.
-Press Y to bring up the list of cheats stored in your SD card or memory card.

### Expected behavior

A list of cheats to enable or disable should appear.

**Comment by Extrems** [comment] 2022-06-04 21:06
Duplicate of issue #678.

**Closed by Extrems** 2022-06-04 21:06 UTC
Labels: duplicate
