### ISSUE TITLE
Phantasy Star Online 1 crashes/game bugs

### ISSUE THREAD

**Issue by HiNu7** [emukidid/swiss-gc#682] opened 2022-05-30 23:39 UTC
On swiss version 1290 using sd2sp. Playing in offline mode the game crashes the gamecube after a few minutes of playing and in game boxes/enemies become un-targetable and you walk through boxes, etc.

**Comment by Extrems** [comment] 2022-05-31 00:49
Duplicate of issue #673. Hopefully I'll have a proper fix out soon enough.

**Closed by Extrems** 2022-05-31 00:49 UTC
Labels: duplicate
