### ISSUE TITLE
990 crashes when initializing network is in Swiss.ini

### ISSUE THREAD

**Issue by epochVHS** [emukidid/swiss-gc#445] opened 2021-01-05 16:30 UTC
I have a GCLoader and an SD2SP2 (for swiss.ini), as well as a broadband adapter. When I replaced boot.iso from 963 to 990, Swiss stopped booting and showed a black screen with white text. I went through my swiss.ini line by line and was able to determine it is the network initialization line that causes the crash.

**Comment by epochVHS** [comment] 2021-01-05 16:30
![image](https://user-images.githubusercontent.com/5022277/103671777-aacc0080-4f7b-11eb-8da9-f1a4bbb6c961.jpeg)
This is the error.

**Comment by Extrems** [comment] 2021-01-05 16:55
Does this happen to be a PAL system with Swiss Video Mode set to 480p?

**Comment by epochVHS** [comment] 2021-01-05 17:01
Yes, although I seem to think I tried with video set to auto and still got a crash. But I can double check that.

**Comment by Extrems** [comment] 2021-01-05 17:31
Duplicate of issue #438.

**Closed by Extrems** 2021-01-05 17:31 UTC
Labels: duplicate
