### ISSUE TITLE
Issue: Alien Hominid (NTSC-U) freezing when loaded through sd2sp

### ISSUE THREAD

**Issue by tyrgyl** [emukidid/swiss-gc#761] opened 2022-12-17 10:58 UTC
### Describe the bug

This is my first bug report.
The game Alien Hominid consistently freezes after starting a game. 
The iso is NTSC U. my Console unit is 001 model. Error reproduces with several iso downloads. Does the same with two sd cards. crash consistent over 240p and 480i. 

Assumed bug observed on latest swiss 0.6 release 1400 with pico boot installed
but also on swiss 0.5 rev 870 using xeno gc

When I burned the game ISO dvd, it runs flawlessly, so i assume it is not motherboard hardware related on my hardware unit. It has no heat issues and i have not observed any other games crashing. 

### Steps to reproduce

Load game via swiss from SD card.
Game - new game
play for less than 60 seconds
Observe console crash.

### Expected behavior

N/A

**Comment by Extrems** [comment] 2022-12-17 13:28
Duplicate of issue #410.

**Closed by Extrems** 2022-12-17 13:28 UTC
Labels: duplicate
