### ISSUE TITLE
High Pitched Noise when using GCVideo

### ISSUE THREAD

**Issue by vaderag** [emukidid/swiss-gc#538] opened 2021-05-29 13:27 UTC
I've just got a GCVideo Adapter and everything is fine once I'm in a game. But when I'm in Swiss I have a constant high pitched white noise that no settings seem to remove... 
Unsure if this is known issue or not but don't see any mention anywhere
Thanks!

**Comment by Extrems** [comment] 2021-05-29 14:21
There shouldn't be any audio coming out. Are you sure it's coming from your speakers?

**Comment by Extrems** [comment] 2021-05-29 19:48
From your forum posts, I've determined this is a duplicate of issue #529.

**Closed by Extrems** 2021-05-29 19:48 UTC
Labels: duplicate

**Comment by vaderag** [comment] 2021-06-08 10:22
Posted this in #529 but if anyone lands here:

I've found a working solution to fix this seamlessly!

Instructions...
Get dolaunch from here: https://github.com/suloku/dolaunch/releases/tag/0.2-dolxz
Stick boot.gci of the standard version onto your memory card to get the DOL to be used with Shinehax
Put Swiss on your SD card (if using SD2SP2 as I am) and rename to autoexec.dol)

Load Shinehax as usual - no terrible beep!
