### ISSUE TITLE
Mario Party 4 Stamp Out Mini-Game Intro slows down

### ISSUE THREAD

**Issue by ScytheandGenesisGames** [emukidid/swiss-gc#640] opened 2022-01-30 00:55 UTC
during Stamp out and as soon you begin the Game the Notepad's intro of it dropping is slow then plays normally when the players are on the pad.

This might be an issue with this mini-game's video cinematic on the Swiss still bugged on the latest version.

Here's a Video to explain how it supposed to run - https://www.youtube.com/watch?v=smVNLEx1u-o

**Comment by Diegorella** [comment] 2022-01-30 19:55
A new update has been made within the access database.
Look for the "show hidden" option
Delete the "Patchs" folder inside the Swiss folder.
 
Watch out! Do not delete the Swiss folder. (Save).

run

sd:/swiss/patches_delete

go on your watch and change the date randomly.
later
turn off the console.

power and update the console's date and time.
restart.

See if the issue is resolved...

**Comment by ScytheandGenesisGames** [comment] 2022-02-12 01:39
here's what I did

Deleted the GMPE - Which is Mario Party 4's Patch folder

then changed the date to something randon and power of the gamecube
then updated the date and went for a full power off then back on

and still the same issue when it repatched the game

**Comment by Diegorella** [comment] 2022-02-16 13:16
can you try a new game dump? or
a different format for the SD.

**Comment by Extrems** [comment] 2022-02-16 22:32
I'm not sure what this game is doing, but it also occurs on GC Loader.

**Comment by Extrems** [comment] 2022-02-17 01:14
This is occurring because the game is copying from uncached memory using load byte instructions, which the processor interface doesn't support as a transfer size.

**Comment by Extrems** [comment] 2022-02-17 14:28
Fixed in a15d594 (r1259).

**Closed by Extrems** 2022-02-17 14:28 UTC
Labels: patcher, game bug
