### ISSUE TITLE
GC Loader doesn't reset to boot.iso

### ISSUE THREAD

**Issue by Sirethief2525** [emukidid/swiss-gc#327] opened 2020-03-17 11:17 UTC
Whenever I use the in game reset option the only way I can get it to function is if i use the igr.dol file, the reboot option kinda works as in it reboots the system but gives me an error message as soon as it does basically making it where I have to power it off anyway. I don't know if this particular issue has been noted before but since I installed my GCLoader the past few revisions I've used have all had this issue. Is there anything that can be done about it? Or is that normal functionality with the GCLoader?

**Comment by Extrems** [comment] 2020-03-17 14:02
You see an error because you were playing an out-of-region game. It doesn't reset to boot.iso.

**Comment by Sirethief2525** [comment] 2020-03-17 20:50
So if I changed the region of my gamecube internally it would fix it? And I
thought it would since my cube and boot.iso are both ntsc-j.

**Comment by Extrems** [comment] 2020-03-17 20:52
It wouldn't fix it. You'd just reset back to the game.

**Comment by Sirethief2525** [comment] 2020-03-17 21:50
So what I'm understanding, is if my cube and boot.iso are the same region the soft reboot option for igr isn't going to work either? So the only way to make it work is with the igr.dol?

**Comment by Extrems** [comment] 2020-03-17 22:44
The error is caused by the region of the game you loaded, because it's trying to load that game again.

**Comment by Sirethief2525** [comment] 2020-03-17 22:52
Okay, I was confused about that. So if I had loaded and ntsc-j game then it would properly reboot back into swiss since that's the main goal I was trying to achieve with igr. The irg.dol works most of the time, but it's kinda picky depending on the game I'm using it with, sometimes it'll just freeze up and then I have to power cycle the system. What would you recommend?

**Comment by Extrems** [comment] 2020-03-17 22:59
No, it would reboot back into the game. This is an issue with the GCLoader.

**Comment by Sirethief2525** [comment] 2020-03-17 23:27
Oh, okay so I need to hop on the GCLoader github page.

**Comment by tjanas** [comment] 2020-06-17 14:48
I have noticed the following with my GCLoader (with Swiss as the boot.iso): after I do an IGR within game, if I select the exit / return to IPL [ ]-> icon on the bottom-right of the Swiss interface, when I am in the GameCube IPL menu, going to Game Play shows the last game that I played, and not the GCLoader boot.iso. At that point, the only way to return to Swiss is power cycling the GameCube.

**Comment by Extrems** [comment] 2020-06-17 14:55
Yes, as was already described...

**Comment by Extrems** [comment] 2021-01-14 02:28
Fixed in e25751d (r1002).

**Closed by Extrems** 2021-01-14 02:28 UTC
Labels: firmware bug, gcloader
