### ISSUE TITLE
Slow loading from Serial Port 2, but games run fine.

### ISSUE THREAD

**Issue by reikitsune** [emukidid/swiss-gc#635] opened 2022-01-14 09:30 UTC
Not sure if it's an issue, or just how swiss works, but it takes a little bit to load into my folders and loads every time it scroll to a new game on the list. Is there a certain way the MicroSD has to be formatted besides being Fat32?

**Comment by Diegorella** [comment] 2022-01-17 02:56
you can try exFAT format to SD bigger in capacity.
but you will have to keep another sd to fat32 if you want to run homebrews.

loading can be long at times, but works fine Natively.

**Comment by emukidid** [comment] 2022-02-17 02:39
This is due to the game banner being read every time from games as they appear in the list. Once they've been loaded once for a particular directory they'll stay resident in memory until you navigate to another directory.

**Comment by vaderag** [comment] 2022-03-02 13:03
Wondering if there is a way to store a cache on the SD? 
I noticed the same and while it doesn't really both me, my game list doesnt really change between boots?

**Comment by Extrems** [comment] 2022-08-11 21:08
Duplicate of issue #264.

**Closed by Extrems** 2022-08-11 21:08 UTC
Labels: duplicate
