### ISSUE TITLE
Medal of Honor Rising Sun black screen

### ISSUE THREAD

**Issue by Nicolas-Miranda** [emukidid/swiss-gc#432] opened 2020-11-15 23:39 UTC
Hi,
    I'm testing a Gamecube DOL-001 with Swiss GC and GCLoader and while trying to start Medal of Honor Rising Sun it get stuck in a black screen. I tried disabling the Video Patches and no change.

Is this game compatible with Swiss GC?

Currently using:

Swiss v0.5r927
GCLoader Firmware ver: 1.1.2

Thanks so much in advance
Regards!!

**Comment by Extrems** [comment] 2021-02-17 20:13
Duplicate of issue #476.

**Closed by Extrems** 2021-02-17 20:13 UTC
Labels: duplicate
