### ISSUE TITLE
Super Smash Bros. Melee FMV Lag

### ISSUE THREAD

**Issue by kingjinxy** [emukidid/swiss-gc#430] opened 2020-11-15 19:49 UTC
Swiss Revision: 963
System: GameCube USA DOL-001
Video: NTSC Composite video to a CRT (video mode not forced on Melee)
Storage: GCLoader with 128GB MicroSD Card fitted into an adapter
Secondary Storage: 32GB MicroSD Card installed in Serial Port 2
Game: Full 1.35GB NTSC-U ISO, Redump-verified

Settings: 
Force video mode: no
Force hor. scale: auto
Force ver. offset: +0
Force ver. filter: auto
Disable Alpha Dithering: Disabled
Force Anisotropic Filter: disabled
Force Widescreen: no
Force text encoding: auto
Invert camera stick: no
Emulated read speed: yes

Issue: When playing back the "How to Play" video (accessible under "Data" on the menu) with Read Speed Emulation enabled, the video falls behind the audio. A few seconds in, the video stutters and is then forever behind the audio.

When I test without Read Speed Emulation, the video plays back fine, with no drops or hitches.
I theorize that the Read Speed Emulation is simply too slow for this video, as it is a full-screen 60FPS encode.
What do you think?

**Comment by Extrems** [comment] 2020-11-15 20:28
Duplicate of issue #414. Cannot reproduce.

**Closed by Extrems** 2020-11-15 20:28 UTC
