### ISSUE TITLE
[Issue]: F-Zero GX Random Reset/Black Screen/Bad Texture Display

### ISSUE THREAD

**Issue by Nicolas-Miranda** [emukidid/swiss-gc#820] opened 2023-07-10 18:42 UTC
### Describe the bug

F-Zero GX is the only game giving problems with random restarts, bad texture image and sudden black screens. 

I couple of months ago I updated Swiss from v0.5r1184 to v0.6r1290 and before the update the game played properly with very rare crashes and I was able to finish it. But after the upgrade I started playing the game this weekend and I'm not able to finish a cup as the game restarts randomly and sometimes shows bad textures (with lines and dots in them). I'm not sure what changed between versions that makes the game to behave in this way.

All the other games run flawlessly in my gamecube as it uses a GCLoader and I also verified the integrity of my F-Zero GX iso file and I tested the JP version which have the same problems as the US version.

I'm playing with an Eon GC MKii and I don't use any graphic enhancements besides the in-game Progressive Scan feature. I also tested without Progressive Scan and disabling all video patches with the same result.

### Steps to reproduce

Just start the game, wait in the intro video or play a cup.

### Expected behavior

Stable gameplay

**Comment by Extrems** [comment] 2023-07-10 20:45
Duplicate of issue #401. Cannot reproduce.
I suspect a hardware defect.

**Closed by Extrems** 2023-07-10 20:45 UTC
Labels: duplicate
