### ISSUE TITLE
[GC Loader] Swiss is not detecting SD Gecko after relaunch Swiss from GameCube BIOS Menu

### ISSUE THREAD

**Issue by ABOhiccups** [emukidid/swiss-gc#427] opened 2020-11-09 03:06 UTC
I'm using both GC Loader and SD Gecko on GameCube.

I turn on GameCube and it auto boot to Swiss and it detected SD Gecko with no issues.

I exit Swiss to GameCube BIOS. After I change Date and Time. I relaunch Swiss from GameCube BIOS Menu. Swiss is not detecting SD Gecko.

I turn off and turn on GameCube and Swiss detected SD Gecko with no issues.

**Comment by Extrems** [comment] 2020-11-09 03:25
Duplicate of issue #309.

**Closed by Extrems** 2020-11-09 03:25 UTC
Labels: duplicate
