### ISSUE TITLE
[Issue]: Virtual Memory Cards not working on Swiss v0.6r1730

### ISSUE THREAD

**Issue by PlayerGameSK** [emukidid/swiss-gc#913] opened 2024-09-20 19:36 UTC
### Describe the bug

I'm trying to use the Virtual Memory Cards feature, but even though a file does get created in the "swiss/saves" folder after enabling it and launching a game, both the BIOS menu and the actual game itself are not detecting the memory card as inserted at all. (says "Nothing is inserted in Slot A / B.")

### Steps to reproduce

1.) Enable the "Emulate Memory Card" setting in "Global Game Settings"
2.) Launch a game and try loading / saving 

### Expected behavior

A virtual memory card getting detected and being usable in the game.

### Add screenshots

![1](https://github.com/user-attachments/assets/8bc9b479-66df-4c13-996c-c93e76c6bfd6)
![2](https://github.com/user-attachments/assets/d6ffa16d-7d2a-4cdd-8f31-2b14501c48cb)
![3](https://github.com/user-attachments/assets/b75a8e6b-5dfd-4095-84f1-ec18dcea6c43)
![4](https://github.com/user-attachments/assets/728e3a1e-3ce1-4a71-8935-51b8af77eeaf)

**Comment by Extrems** [comment] 2024-09-20 22:50
Duplicate of issue #493.

**Closed by Extrems** 2024-09-20 22:50 UTC
Labels: duplicate
