### ISSUE TITLE
Rainbow Six 3 - Black Screen

### ISSUE THREAD

**Issue by earthprime** [emukidid/swiss-gc#584] opened 2021-09-20 15:31 UTC
Rainbow Six 3 drops to a black screen (resolution drops to 0) upon loading the first stage.  This happens with both composite cables and HD cables (via HDMI adapter).  The issue is either Swiss or GCLoader.  Composite cables were used on a Commodore64 monitor (from 1983), so issue is verified to not be caused by modern displays.

**Comment by Extrems** [comment] 2021-09-20 23:02
Cannot reproduce. Possibly a duplicate of issue #420.

**Closed by Extrems** 2021-09-20 23:02 UTC
Labels: invalid

**Comment by earthprime** [comment] 2021-09-21 01:49
Updated with detailed steps to reproduce - posted in issue #420.

**Comment by Extrems** [comment] 2021-09-21 01:50
This is not a supported hardware configuration. Use clean boot (L+A) if necessary.
