### ISSUE TITLE
Shinehax Audio Issue

### ISSUE THREAD

**Issue by vaderag** [emukidid/swiss-gc#541] opened 2021-06-07 10:07 UTC
High pitched audio when loading via Shinehax

**Comment by magu** [comment] 2021-06-07 11:23
Ain't this also a likely dupe of #529 ?

**Comment by emukidid** [comment] 2021-06-07 11:25
Duplicate of #529

**Closed by emukidid** 2021-06-07 11:25 UTC

**Comment by vaderag** [comment] 2021-06-08 10:21
Posted this in #529 but if anyone lands here:

I've found a working solution to fix this seamlessly!

Instructions...
Get dolaunch from here: https://github.com/suloku/dolaunch/releases/tag/0.2-dolxz
Stick boot.gci of the standard version onto your memory card to get the DOL to be used with Shinehax
Put Swiss on your SD card (if using SD2SP2 as I am) and rename to autoexec.dol)

Load Shinehax as usual - no terrible beep!
