### ISSUE TITLE
[Question]: Unable to Save Configurations

### ISSUE THREAD

**Issue by GGCrick** [emukidid/swiss-gc#664] opened 2022-04-08 15:22 UTC
### Describe your question

Using Datel's SD Media Loader to boot swiss [v0.6r1290] from 2gb SD [FAT] in slot B (using the autorun feature and Datel's supplied SD Reader).

Swiss boots and I am able to use Swiss to force progressive etc (PAL Cube) as required.

Configurations Device set to Slot B so that settings should be saved. (Current game disc will only read memory cards from slot A).

On reboot, swiss has not saved any configuration changes. 

No ini file recorded on the SD card when checked via PC.

Am I missing any additional options or features that are preventing the configurations being saved?

Thank you for your time.

**Comment by Extrems** [comment] 2022-04-08 15:51
And there were no warnings or errors along the way?

**Comment by GGCrick** [comment] 2022-04-08 21:15
> And there were no warnings or errors along the way?

None other than the inability to save config notification.

If it wasn't for the issue described, the program runs perfectly.

**Comment by Extrems** [comment] 2022-04-08 21:18
It can't be running perfectly if you're also getting "No writable device available. An SD Card Adapter is necessary in order for patches to survive application restart."
Are you able to navigate to the SD card device? It should also be the default device when you boot Swiss.

**Comment by GGCrick** [comment] 2022-04-08 21:45
Thank you for the quick response.

I don't believe I've seen that warning, though as a new user may have perhaps missed it along the way?

I am able to attempt to open the SD from the device selection (where it appears on opening Swiss). On attempting to open the SD however, (following a short bar attempting to open the device) it disappears from the selection options leaving only DvD and system.

Once I have tried to save a config preference, resulting in the above mentioned failure to save config warning, the SD option is returned to device selection.

Otherwise the only notable information presented is when opening the game from DvD.

I am first told that the video mode is set to my preference (NTSC 480P), followed by bar progression for checking the game, then bar progression for patching file 1/3 apploader.img [119kb], bar progression once again for loading dol, do not remove SD card - slot b and then finally the game boots.

Thank you for your continued assistance.

**Comment by Extrems** [comment] 2022-04-08 21:48
Duplicate of issue #299.

**Closed by Extrems** 2022-04-08 21:48 UTC
Labels: duplicate

**Comment by GGCrick** [comment] 2022-04-08 21:56
Ah, I missed that thread.

Thank you for your time. I will look into different SD card options and go from there.
