### ISSUE TITLE
[Issue]: gamecube controller refusing to work in swiss

### ISSUE THREAD

**Issue by kamikazilucas** [emukidid/swiss-gc#898] opened 2024-08-14 08:45 UTC
### Describe the bug

controller not working within swiss, it works fine in all games and in other menus but only in swiss it just dosent respond 

### Steps to reproduce

launch the program

### Expected behavior

controller to respond

**Comment by Extrems** [comment] 2024-08-14 15:28
Duplicate of issue #428.

**Closed by Extrems** 2024-08-14 15:28 UTC
Labels: duplicate

**Comment by lauti29** [comment] 2024-08-14 17:38
> ### Describe the bug
> 
> controller not working within swiss, it works fine in all games and in other menus but only in swiss it just dosent respond
> ### Steps to reproduce
> 
> launch the program
> ### Expected behavior
> 
> controller to respond
> ### Relevant log output
> 
> _No response_
> ### Add screenshots
> 
> _No response_

if you are booting swiss on a wii you need a gamecube game disc on the tray for it to work, at least in my case

**Comment by kamikazilucas** [comment] 2024-08-14 19:12
i do have a gamecube disc inside the wii, and the controller is not chinese its an official controller
