### ISSUE TITLE
Add support for multiple partitions

### ISSUE THREAD

**Issue by criger** [emukidid/swiss-gc#379] opened 2020-08-09 17:50 UTC
This has been asked previously, but not in the correct way.
Currently, if you have two or more partitions on an SD-card, only the first partition created will be displayed in Swiss.

The reason it would be nice to have this feature, is when using e.g (as in my situation) snes9xgx and/or vbagx/mGBA.
These emulators cannot read cards that are formatted with exFAT or FAT32. The card must be formatted with FAT16, which has a limit on 2 GB.

So when I want to play snes/gba games on my gamecube through Swiss, I have to put them on the small 2 GB sd-card located inside the Memory Card.
The bus speed here is way slower than the bus speed on the Serial port. This means that some games may experience drops in frames and/or stuttering sound/image.

Prior to making this thread, I tested with snes9xgx on a small FAT16 partition located in the sd-card in the serial port, and the games (also located in the same partition) ran without any problems.

The gamecube ISOs, which were located in a second partition on the same SD-card, did not display at all in Swiss.

So, as you hopefully understand:
Adding support for listing multiple partitions on an SD-card, would simply be awesome.

Of course, this situation would probably not happen if I were to use GCLoader as I could then use the SD card loader on top of the gamecube in addition to the one inside the serial port. 
But for users who would like to keep their Gamecube in an original state, this feature would simply R O C K !

**Comment by Extrems** [comment] 2020-08-09 17:56
> The bus speed here is way slower than the bus speed on the Serial port. This means that some games may experience drops in frames and/or stuttering sound/image.

This is wrong. They're the very same thing.

**Comment by Extrems** [comment] 2020-08-09 17:57
Duplicate of issue #292.

**Closed by Extrems** 2020-08-09 17:57 UTC
