### ISSUE TITLE
Memory card sd card adapter dismounts after swiss finishes initializing disc drive[Issue]: 

### ISSUE THREAD

**Issue by Boutime** [emukidid/swiss-gc#838] opened 2023-10-03 23:18 UTC
### Describe the bug

Gamecube has picoboot and boots swiss from sd card
Immediately after initializing disc drive, the light goes out on sd card adapter
In order for swiss to recognize sd card, I have to unplug and replug adapter

### Steps to reproduce

Boot swiss from sd card adapter with picoboot
Sd card will dismount after disc drive initialization

### Expected behavior

I expect the sd card to not dismount

**Comment by Extrems** [comment] 2023-10-03 23:36
Duplicate of issue #299.

**Closed by Extrems** 2023-10-03 23:36 UTC
Labels: duplicate

**Comment by Boutime** [comment] 2023-10-04 01:01
Ran the template.dol
Results are:

_io_gcsda 0 _ioWPFlag 0
_io_gcsdb 0 _ioWPFlag 0
_io_gcsd2 0 _ioWPFlag 1

What do these results mean
