### ISSUE TITLE
Hitman !

### ISSUE THREAD

**Issue by jeffmaas4887** [emukidid/swiss-gc#451] opened 2021-01-11 21:36 UTC
I posted this here for a reason and keeps getting deleted with no F*cking explanation!

Hitman 2 forces itsef closed at the mani menu screen please Fix it!

**Comment by craysiii** [comment] 2021-01-11 21:44
This is not the way to go about getting your issue resolved.

They already explained that they could not reproduce the issue and to check that you have a valid dump. You should check redump database to compare MD5/SHA hashes with your current ISO to verify its correct.

I do not represent the swiss team btw, I am just a simple user, but your incessant opening of issues and your language is quite frankly unacceptable. These people don't serve you, they are kind enough to work on this project and provide us with it free of charge. They deserve more respect.

**Comment by jeffmaas4887** [comment] 2021-01-11 21:52
They could have said something instead of nonstop deleting my post! ANd by the way Fuck You Asshole!

**Comment by emukidid** [comment] 2021-01-12 12:36
@jeffmaas4887 - there was a comment [here](https://github.com/emukidid/swiss-gc/issues/449#issuecomment-758225253). Closing again.

**Closed by emukidid** 2021-01-12 12:36 UTC
