### ISSUE TITLE
[Issue]: sandisk ultra 256gb on sd2sp2 for not reading the latest update.

### ISSUE THREAD

**Issue by Zeckeries00** [emukidid/swiss-gc#908] opened 2024-08-26 22:40 UTC
### Describe the bug

Sandisk ultra 256GB on sdsp2 por does not read swiss 1712... when I remove and insert the sd card from the adapter, it reads, but gauntlet slow during gameplay (there are no other games like this). I'm using swiss in an older version.

### Steps to reproduce

gauntlet starts up in slow motion... and continues like this during gameplay (problem only present in the current update)

### Expected behavior

I just want to turn on the gamecube and play games with maximum compatibility. Swiss was what revived my gamecube this year... keep improving Swiss

**Comment by Extrems** [comment] 2024-08-27 01:30
Duplicate of issue #890.

**Closed by Extrems** 2024-08-27 01:30 UTC
Labels: duplicate
