### ISSUE TITLE
[Issue]: Problem with swiss 1695 바이오하자드3 ,마리오카트 Error message 등

### ISSUE THREAD

**Issue by 2006MASTER** [emukidid/swiss-gc#901] opened 2024-08-20 10:05 UTC
### Describe the bug

There was no problem with swiss 1668 versions such as Biohazard3 and Mario Kart, but in 1695 versions, there is a problem that comes out to turn off the power after the Eremes or not coming out of the black screen. For those of you who have experienced the same problem, how did you solve it? Is the answer just to go back to the lower version?

### Steps to reproduce

There was no problem with swiss 1668 versions such as Biohazard3 and Mario Kart, but in 1695 versions, there is a problem that comes out to turn off the power after the Eremes or not coming out of the black screen. For those of you who have experienced the same problem, how did you solve it? Is the answer just to go back to the lower version?

### Expected behavior

There was no problem with swiss 1668 versions such as Biohazard3 and Mario Kart, but in 1695 versions, there is a problem that comes out to turn off the power after the Eremes or not coming out of the black screen. For those of you who have experienced the same problem, how did you solve it? Is the answer just to go back to the lower version?

### Relevant log output

```shell
There was no problem with swiss 1668 versions such as Biohazard3 and Mario Kart, but in 1695 versions, there is a problem that comes out to turn off the power after the Eremes or not coming out of the black screen. For those of you who have experienced the same problem, how did you solve it? Is the answer just to go back to the lower version?
```

### Add screenshots

There was no problem with swiss 1668 versions such as Biohazard3 and Mario Kart, but in 1695 versions, there is a problem that comes out to turn off the power after the Eremes or not coming out of the black screen. For those of you who have experienced the same problem, how did you solve it? Is the answer just to go back to the lower version?

**Comment by Extrems** [comment] 2024-08-20 16:01
Duplicate of issue #845.

**Closed by Extrems** 2024-08-20 16:01 UTC
Labels: duplicate
