### ISSUE TITLE
Star Fox Adventures visual error

### ISSUE THREAD

**Issue by TonchMS** [emukidid/swiss-gc#368] opened 2020-07-23 06:42 UTC
Star Fox Adventures displays visual errors with the torches at the very beginning of the game (Krazoa Palace, after the cutscenes with General Scales). Running the game through Swiss causes the[ glow around the torches to be seen through walls/objects/floors](https://i.imgur.com/zOCExsD.jpg). Booting straight into the game as boot.iso stops this from happening.

The correct behavior seems to be that the entire glow effect of the torches are seen until they are blocked from view, at which point they fade. This doesn't happen, or happens erratically, when run through Swiss. I tried all kinds of settings including disabling video patches, but I haven't found anything that helped.

**Comment by Extrems** [comment] 2020-07-23 17:09
This is caused by a workaround for a system lockup that occurs when the depth buffer is peeked during a copy operation, which is most typically encountered in Super Mario Sunshine. More research is needed.

**Comment by Extrems** [comment] 2020-08-17 02:27
Fixed in 98f1562 (r880).

**Closed by Extrems** 2020-08-17 02:27 UTC
Labels: bug, hardware erratum, help wanted, hypervisor
