### ISSUE TITLE
Config persistence of cheat selections

### ISSUE THREAD

**Issue by patters-syno** [emukidid/swiss-gc#478] opened 2021-02-18 14:26 UTC
Having recently been using OpenPS2Loader, I think it would be very useful to have Swiss persist the cheat selections for each game - particularly considering 16:9 widescreen codes. I know there's an option to have Swiss load **all** cheats that are present, but then you'd have to remove any other cheats you might want occasionally from the text files. Having to go into the cheat menu every time when loading a game is fine for us geeks, but it does makes it a bit less kid-friendly. In fact, a kid mode where config changes are impossible would make a great enhancement too.

**Comment by Extrems** [comment] 2021-02-18 15:15
Duplicate of issue  #345.

**Closed by Extrems** 2021-02-18 15:15 UTC
Labels: duplicate
