### ISSUE TITLE
Luigi's Mansion bug

### ISSUE THREAD

**Issue by pcaudill3323** [emukidid/swiss-gc#796] opened 2023-03-30 14:49 UTC
After the last update the game does not load (GCLoader) you can select the game and then it goes back to the main menu, Bummer.

**Comment by Extrems** [comment] 2023-03-30 15:19
Cannot reproduce. I suspect you enabled disc read speed emulation.

**Comment by Extrems** [comment] 2023-03-30 15:45
Duplicate of issue #732.

**Closed by Extrems** 2023-03-30 15:45 UTC
Labels: duplicate
