### ISSUE TITLE
Star Wars Rogue Squadron III: Rebel Strike

### ISSUE THREAD

**Issue by GAMECUBE-N64** [emukidid/swiss-gc#498] opened 2021-03-15 17:48 UTC
Using a Brand new Sandisk Extreme Micro Sd card for Virtual memory in Slot b and I get this message.

Memory Card A:This Memory Card is damaged and cannot be used for this game.

I have done other saves on the same card and there is no problems with those.

Just this one.

**Comment by Extrems** [comment] 2021-03-15 18:08
Duplicate of issue #465.

**Closed by Extrems** 2021-03-15 18:08 UTC
Labels: duplicate
