### ISSUE TITLE
[Question]: 

### ISSUE THREAD

**Issue by Silfversail** [emukidid/swiss-gc#657] opened 2022-03-20 18:27 UTC
### Igr compatability list?

Hi!
Im new to swiss and have a question about igr support. Some games like Resident Evil 2 and Mario Sunshine gets stuck in a black screen or gets thrown back to the ipl. Is there a known compatibility list for these games or is there a problem on my end? I use a save game hack and run swiss on an sd2sp2 (Pal system).
Thank you for your time and awesome work! The Gamecube has become my favorite system thanks to you!  

_No response_

**Comment by Extrems** [comment] 2022-03-20 18:31
Duplicate of issue #364.

**Closed by Extrems** 2022-03-20 18:31 UTC
Labels: duplicate
