### ISSUE TITLE
[Feature request]: Double byte fonts (such as Japanese) support

### ISSUE THREAD

**Issue by SoukinOKATU** [emukidid/swiss-gc#818] opened 2023-06-30 12:57 UTC
### Describe the feature

I am an Asian player currently using NTSC-J'Gamecube and most of my games are in Japanese. However, SWISS does not support Japanese and other double byte fonts. When displaying the instructions for these games, they are all garbled. I hope to add support for Japanese and other double byte fonts in the future

**Comment by Extrems** [comment] 2023-06-30 14:11
Duplicate of issue #702.

**Closed by Extrems** 2023-06-30 14:11 UTC
Labels: duplicate
