### ISSUE TITLE
[Feature request]: GameID adjust for Memcard Pro GC

### ISSUE THREAD

**Issue by THitsu10** [emukidid/swiss-gc#801] opened 2023-04-16 22:50 UTC
### Describe the feature

currently the gameIDs look like G2ME0100, what is the purpose of the 00 on the back end of the actual gameID G2ME01. as far as I can tell is the 00 is the revision number of the title being used. shouldn't the newer revisions be backwards compatible with older revisions? so why not have the default be just the 6 digit gameID?

**Comment by Extrems** [comment] 2023-04-16 22:59
Duplicate of issue #785.

**Closed by Extrems** 2023-04-16 22:59 UTC
Labels: duplicate
