### ISSUE TITLE
[Issue]: Memory Card Emulation not working with ETH2GC Memory Slot Adapter

### ISSUE THREAD

**Issue by teconmoon** [emukidid/swiss-gc#884] opened 2024-07-14 00:24 UTC
### Describe the bug

I purchased an ETH2GC adapter that plugs into an available memory card slot instead of the SP2 port. When Memory Card Emulation is enabled and the ETH2GC adapter is plugged into either Slot 1 or Slot 2, the game in question says that there's no memory card present regardless of whether or not BBA Emulation is enabled. In any case, BBA emulation does appear to function with this version, just at the cost of Memory Card Emulation.

### Steps to reproduce

1. Plug the ETH2GC memory card slot adapter into either memory card slot
2. Boot the latest version of Swiss
3. Enable memory card emulation
4. Optionally, enable BBA Emulation
5. Boot any game
6. Emulated memory card won't be detected

### Expected behavior

The emulated memory card should be detected regardless of the presence of the ETH2GC memory card slot adapter. I would assume that this doesn't happen with an ETH2GC SP2 adapter, but I don't have one to test with.

**Comment by Extrems** [comment] 2024-07-14 01:54
Duplicate of issue #493.

**Closed by Extrems** 2024-07-14 01:54 UTC
Labels: duplicate

**Comment by teconmoon** [comment] 2024-07-14 02:52
@Extrems sorry for the duplicate. I'd seen that thread, but couldn't figure out how it was related.

**Comment by Extrems** [comment] 2024-07-14 02:56
This is the order in which features are given priority:

1. Emulate Audio Streaming
2. Emulate Read Speed (enabled by default for Tales of Symphonia)
3. Emulate Broadband Adapter (enabled by default for games supporting it)
4. Emulate Memory Card

There aren't enough resources to support two (or more) of these at once.

**Comment by teconmoon** [comment] 2024-07-14 03:04
Ah I see, thanks for the breakdown!
