### ISSUE TITLE
[Issue]: Loud noise when booting from memory card

### ISSUE THREAD

**Issue by Pearlh2hoe** [emukidid/swiss-gc#794] opened 2023-03-28 16:03 UTC
### Describe the bug

every time i boot swiss on my PAL gamecube with Shinehax, i hear a noise (similar to the wii crash sound) the intensity varies between menus, in the latest update it seems to be quieter on the main menu and louder on the device selection menu.

### Steps to reproduce

boot swiss ig

### Expected behavior

no loud noise

**Comment by Extrems** [comment] 2023-03-28 18:08
Duplicate of issue #529.

**Closed by Extrems** 2023-03-28 18:08 UTC
Labels: duplicate
