### ISSUE TITLE
How to autoboot an ISO from HyperBoot/Swiss upon power-up?

### ISSUE THREAD

**Issue by TheInfernolab** [emukidid/swiss-gc#335] opened 2020-05-06 05:54 UTC
Per my post at GC-Forever ( https://www.gc-forever.com/forums/viewtopic.php?f=25&t=4617 ) what I seek is currently not possible with Swiss, so I was directed to create an issue on this tracker.

My goal:
Upon power-up of GameCube, immediately launch a game ISO file that's on a microSD card on an SD2SP2. Always the same game; the card has just 1 game ISO on it. No need for a menu or options or anything.

My setup:
GameCube DOL-001
HyperBoot installed in GC
SD2SP2 in serial port
microSD card in SD2SP2
"swiss_r827-compressed.dol" in "HYPERBOOT" directory on microSD card
A game ISO file on the same microSD card, in the root directory

When I power on the GC, I successfully get the Swiss menu.
Within Swiss, I can manually navigate to & launch the desired ISO from the microSD card.

Can I make this ISO **automatically** launch when Swiss boots?

Is there an INI file, macro file, or the like for Swiss that will skip the Swiss menu & instead immediately launch my ISO?

-------

Or, alternate path, if it's easier or makes more sense:
Make a DOL from my game ISO & just boot that DOL from HyperBoot, bypassing Swiss altogether...?
When I launch the ISO from Swiss, I believe that one of the quick progress bars that zips by says that a DOL is being created from my game ISO & then the game is launched.
Can Swiss generate a DOL from an ISO & save it to the card?

Thank you!
-Jason

**Comment by Extrems** [comment] 2020-06-13 05:08
Duplicate of issue #259.

**Closed by Extrems** 2020-06-13 05:08 UTC
