### ISSUE TITLE
SD Card adapter: Trouble with Memory card emulation

### ISSUE THREAD

**Issue by adlroux** [emukidid/swiss-gc#512] opened 2021-03-29 14:08 UTC
I own a GameCube with a GC Loader, a Carby HDMI output dongle, a SD Card adapter connected to Slot 1 and n official Nintendo Memory Card in Slot 2. For a long time, I was using the memory Card emulator in Slot 1 (on the SD Card) and it was working fine.

Two versions ago, the changelog mentioned this: "Disable memory card in the same slot as SD card for the time being". When I tested it, indeed, none of my saves made on the SD Card were available anymore. So, I had to stay one version behind to keep it working.

For the sake of curiosity, I'd be interested to know the reason why it was disabled, and what kind of workaround can I do to make my save file still accessible with latest versions of Swiss. Thanks a lot

**Comment by Extrems** [comment] 2021-03-29 14:49
It was disabled because the asynchronous version cannot hold a recursive lock on the EXI channel. You need to use a different slot for your SD card adapter. Both slots can be used with a SD2SP2.

**Comment by adlroux** [comment] 2021-03-29 15:29
I see, thanks for your answer. If I switch the SD Card Adapter in Slot 2, will the Memory Card emulation be shown in Slot 1 in-game? Is there any configuration change I need to do?

**Comment by Extrems** [comment] 2021-03-29 15:32
Both slots are emulated regardless of the slot used for the SD card adapter. You should change the configuration device in Swiss beforehand.

**Comment by adlroux** [comment] 2021-03-29 15:39
Oo I see :) How do I do that?

Also, really, Id like to thank you for this wonderful tool. You do some great work here, really. I wish you one day to crack the problem that is writing directly on the GC Loader. Good luck!

**Comment by Extrems** [comment] 2021-03-29 15:41
You can find it under global settings.

**Comment by JinxDojo** [comment] 2021-06-25 22:51
Is this the best issue to watch regarding progress on the possibility of overcoming the "locking handle" issue (so that both slots can be emulated when using an SDGecko)? Or is there another? (A quick search doesn't reveal anything obvious.)

**Comment by Extrems** [comment] 2021-11-04 05:11
Duplicate of issue #611.

**Closed by Extrems** 2021-11-04 05:11 UTC
Labels: duplicate
