### ISSUE TITLE
The Sims 2

### ISSUE THREAD

**Issue by TH3GOD88** [emukidid/swiss-gc#397] opened 2020-09-09 19:05 UTC
Using either v0.5r906 or v0.5r888, I cannot get Swiss to see the cheat file, but it sees any other cheat file I try to use for other games. I don't know if I am doing something wrong. I have the file as G4ZE69.txt with it's code in there. I've tried to use AR code in the file and WiiRD. Do I need the name of the game in anyway?

**Comment by Extrems** [comment] 2020-12-04 23:15
Duplicate of issue #436.

**Closed by Extrems** 2020-12-04 23:15 UTC
Labels: bug, cheats, duplicate
