### ISSUE TITLE
Trying to get Medal of Honor: Rising Sun working on Swiss

### ISSUE THREAD

**Issue by blakezilla** [emukidid/swiss-gc#476] opened 2021-02-16 20:33 UTC
Hi there, have done a bit of bug testing and research on it and couldn't find the answer.

Setup: Latest Swiss (Swiss v0.5r1026), GC Loader (Latest Firmware), NTSC J Gamecube

Trying to run Medal of Honour: Rising Sun on it. Most times it hangs at a black screen then resets to Swiss.

After playing around with the settings, it would only reliably run when forced to run at 576i, but then during FMVs it would stutter.

One of the big issues, however is that it does not recognize the Virtual Memory Card in Slot A

My questions: 
a) What would the reason be for it not to run normally?
b) What is the issue with the Virtual Memory Card, and can I fix it on my end?

Thanks so much for the work you do!

**Comment by Extrems** [comment] 2021-02-16 21:10
You must enable "Disable Video Patches" for this game at this time.

**Comment by blakezilla** [comment] 2021-02-16 22:32
Is that in the overall Game Settings, or individual settings? I believe I tried that earlier in my testing, but couldn't get passed the initial boot. I will try when I get back from work.

**Comment by blakezilla** [comment] 2021-02-17 00:14
So does that turn off video patches for all games or just this title?

Would it still work if I had a physical memory card?

**Comment by blakezilla** [comment] 2021-02-17 06:08
Hi, I just tried disabling Video Patches, it would just black screen and revert back to Swiss. The only way I have successfully got it to boot is when Forced into 576i. The FMVS stutter but does run.

**Comment by Extrems** [comment] 2021-02-17 17:32
I'm unable to reproduce this issue with either a full .iso or a .nkit.iso, and with or without boot through IPL.

**Comment by Extrems** [comment] 2021-02-17 20:12
Memory card issue fixed in 5b9f422 (r1038).

**Comment by blakezilla** [comment] 2021-02-17 20:37
SO just to clarify, you were able to boot the game with no issues with the memory card just by disabling video patches?

**Comment by Extrems** [comment] 2021-02-17 20:37
Yes.

**Comment by blakezilla** [comment] 2021-02-17 20:41
Was there anything else I needed to disable in the settings? I am familiar with Swiss, but it just isn't working

**Comment by Extrems** [comment] 2021-02-25 20:31
NTSC-J issue fixed in e416ecf (r1045).

**Comment by Extrems** [comment] 2021-04-28 18:34
Fixed in 644232c (r1085).

**Closed by Extrems** 2021-04-28 18:34 UTC
Labels: bug, patcher
