### ISSUE TITLE
Magic Path PSX to GC Adapter

### ISSUE THREAD

**Issue by chemaperez** [emukidid/swiss-gc#628] opened 2021-12-14 18:04 UTC
I have an issue regarding the Magic Path PSX to GC adapter. It has always worked fine on my gamecube. It also works fine in the Swiss menu. But it doesn't work at all on games loaded via Swiss or in GBI. 

![magic-path-ps2-psx-controller-adapter-auf-gc-wii-wii-controllers-1931-700x700](https://user-images.githubusercontent.com/21042649/146054454-f92da441-2618-4c25-a93b-6e0736870d76.jpg)

**Comment by Diegorella** [comment] 2021-12-16 20:58
I believe your problem will be better answered, and solved if you post the question on the official website gc-forever.com
look for the correct tab; as this is a problem that perhaps is not related to the Swiss itself.

**Comment by Extrems** [comment] 2022-02-17 14:33
Duplicate of issue #428.

**Closed by Extrems** 2022-02-17 14:33 UTC
Labels: duplicate
