### ISSUE TITLE
FTP access ist not working and SMB config issues

### ISSUE THREAD

**Issue by BorgNumberOne** [emukidid/swiss-gc#459] opened 2021-01-22 20:30 UTC
Hi

Some days ago, at home I found a well packed GameCube (from my wife ;) )in a box in the attic.

Playing games is okay, but I thought: what can be done furthermore except playing games.

So, I began to read many stuff about gc-linux and homebrew and AND SWISS
and I began to buy accessoires like SD-card adapters (for GameCube front and bottom connections) and a GameCube HDMI adapter with gcvideo firmware.
--> really sharp image quality. :-D

First of all, I would like to say that Swiss is a really great utility (together with cleanrip) to build up a diskless GameCube games library.
Furthermore it is amazing to see that the gamecube (with the help of swiss - *thumbs up*) is running non-Nintendo-stuff:

homebrew (pouet.net -> gamecube),
snes9xgx-gc
vbagx-gc,
scummvm-gc,
wiicross-gc,
240p-test-suite,
joysticktestsdl12,
mplayer-gc,
megaloader (https://www.google.com/search?q=%22megaloader%22+gamecube)
etc...

THUMBS UP!!!

Today I got a broadband adapter, could successfully install it to the GameGube...:

![IMG_20210122_145421](https://user-images.githubusercontent.com/77854382/105537730-a2e9bb80-5cf2-11eb-8236-1c68fa752531.jpg) ![IMG_20210122_144926356](https://user-images.githubusercontent.com/77854382/105537774-b432c800-5cf2-11eb-9b4b-166ed84935e5.jpg)
![IMG_20210122_145206](https://user-images.githubusercontent.com/77854382/105537758-ab41f680-5cf2-11eb-94a9-943f76a0aa39.jpg)
![IMG_20210122_145238](https://user-images.githubusercontent.com/77854382/105537746-a7ae6f80-5cf2-11eb-81c3-a0625c7d7de9.jpg)
![IMG_20210122_145120](https://user-images.githubusercontent.com/77854382/105537763-af6e1400-5cf2-11eb-9ad4-3aca382424ff.jpg)
![IMG_20210122_151328973](https://user-images.githubusercontent.com/77854382/105537641-83eb2980-5cf2-11eb-8625-2a4a64333f68.jpg)

...and I could successfully reach the http server of the running swiss homebrew app on the GameCube - here is a screenshot of accessing swiss http server from android mobile phone:

![Screenshot_20210122-211232](https://user-images.githubusercontent.com/77854382/105540597-c0b91f80-5cf6-11eb-8cb9-815717e0de09.png)
_____

Code of the swiss generated page:

`<html>                                <head><title>Swiss httpd page</title></head>                                <body>                                <a href="dvd.iso">Dump DVD Disc</a><br> 							   <a href="ipl.bin">Dump IPL Mask ROM</a><br>                                </body>                                </html>`

So, this direction (accessing the GameCube via http:// from mobile phone or notebook) is working very well.

However, if I want to access a FTP server, swiss freezes and the displayed time in the upper left corner stops running.

Second problem:
Well, if I would like to do any samba (SMB) related stuff, then it is confusing that this will be displayed on the one hand...

Device Selection
SMB 1.0/CIFS
Configurable via the settings screen

...but on the other hand there are no SMB related stuff in/at the settings screen.

![IMG_20210122_204751161](https://user-images.githubusercontent.com/77854382/105539539-2e644c00-5cf5-11eb-9105-62fdf19bf637.jpg)
![IMG_20210122_205002444](https://user-images.githubusercontent.com/77854382/105539505-21dff380-5cf5-11eb-9082-1a311d1d3075.jpg)
![IMG_20210122_205033875](https://user-images.githubusercontent.com/77854382/105539470-1391d780-5cf5-11eb-8763-d21f3163d910.jpg)

My GameCube specs are:

Swiss v0.5 rev: 994
![IMG_20210122_151039126](https://user-images.githubusercontent.com/77854382/105537678-906f8200-5cf2-11eb-9f9e-e6c846aeb51c.jpg)

Nintendo GameCube DOL-001

IPL VERSION
PAL Revision 1.0

VIDEO MODE
PAL 567p

AUDIO
Stereo

Language
German

CPU PVR
00083214

CPU ECID
0D96200D:A800C089:AA7C2868:FE1B3EE0

SLOT-A
Memory Card

SLOT-B
SD Card Adapter
*** 2GByte - FAT 16 formatted via Windows8.1,
displayed values in swiss:
Total: 1.87GB
Free: 1.17GB
Used: 716.41 ***

SERIAL PORT 1
BBA (192.168.178.74)
*** This IP address was not entered manually.
It shows that the local network DHCP service of my cable modem router seems to work with the gamecube very well. ***

FTP server is: 192.168.178.1 (built-in FTP server feature of my "FRITZ!Box 6490 Cable" router, same local network)

SERIAL PORT 2
SD Card Adapter
*** 400GByte - FAT 32 formatted via "guiformat/fat32format",
displayed values in swiss:
Total: 366.70GB
Free: 346.17GB
Used: 20.53GB ***

DRIVE INTERFACE
Disc Drive 06 2001/08 (61)

PROGRESSIVE VIDEO
Yes

CURRENT MEDIUM
SD Card - SP2

CONFIG MEDIUM
SD Card - Slot B

**Comment by Extrems** [comment] 2021-01-22 21:16
Duplicate of issue #362.

**Closed by Extrems** 2021-01-22 21:16 UTC
Labels: duplicate
