### ISSUE TITLE
Gamecube IPL memory card manager Error while emulating memory cards

### ISSUE THREAD

**Issue by TerrienDJV5** [emukidid/swiss-gc#917] opened 2024-09-27 19:17 UTC
### Describe the bug

Error on GameCubes IPL memory card manager while using emulated memory cards but swiss is launched from memory slot B

I believe its something to do with swiss tring to pass through the device in slot B, but cant because it running from slot B

### Steps to reproduce

Setup:
Enable boot through ipl
Enable emulate memory cards
Have swiss running from sdgecko in memory slot B

Actions:
Load a game in swiss
Hold A during gamecube animation to enter its menu before the game starts
Head down to memory card management screen and open it

An error message will appear stating that an error has occurred and to read the user manual

### Expected behavior

No Error and ability to manage games on emulated memory cards

### Relevant log output

```shell
# Swiss Configuration File!
# Anything written in here will be lost!

#!!Swiss Settings Start!!
SD/IDE Speed=32MHz
System Sound=Stereo
Screen Position=+0
System Language=English
Swiss Video Mode=Auto
Enable Debug=No
Hide Unknown file types=No
Stop DVD Motor on startup=No
Enable WiiRD debug=No
Enable File Management=No
Disable MemCard PRO GameID=No
Disable Video Patches=None
Force Video Active=No
Force DTV Status=No
Pause for resolution change=No
SMBUserName=
SMBPassword=
SMBShareName=
SMBHostIP=
AutoBoot=No
AutoCheats=No
InitNetwork=Yes
IGRType=Disabled
AVECompat=GCVideo
RT4KOptim=No
FileBrowserType=Standard
BS2Boot=Yes
FTPUserName=
FTPPassword=
FTPHostIP=
FTPPort=21
FTPUsePasv=No
FSPHostIP=
FSPPort=21
FSPPassword=
FSPPathMTU=1500
BBALocalIP=192.168.8.231
BBANetmask=20
BBAGateway=192.168.0.1
BBAUseDHCP=Yes
ShowHiddenFiles=No
RecentListLevel=On
GCLoaderHWVersion=0
GCLoaderTopVersion=
Autoload=
FlattenDir=*/games
Force Video Mode=Auto
Force Horizontal Scale=Auto
Force Vertical Offset=+0
Force Vertical Filter=Auto
Force Field Rendering=Auto
Disable Alpha Dithering=No
Force Anisotropic Filter=No
Force Widescreen=No
Force Polling Rate=No
Invert Camera Stick=No
Swap Camera Stick=No
Digital Trigger Level=0
Emulate Audio Streaming=Auto
Emulate Read Speed=No
Emulate Memory Card=Yes
Emulate Broadband Adapter=No
Prefer Clean Boot=No
#!!Swiss Settings End!!
```

### Add screenshots

![20240927_151029](https://github.com/user-attachments/assets/70c8ee08-689f-4d07-899c-32938870c1e2)
![20240927_151102](https://github.com/user-attachments/assets/18a62e97-545a-4ca5-9a10-00a5ffd6ac88)

**Comment by Extrems** [comment] 2024-09-27 20:38
Fixed in e6cce88 (r1732).

**Closed by Extrems** 2024-09-27 20:38 UTC
Labels: bug, hypervisor

**Comment by osyu** [comment] 2024-09-29 19:33
Mentioning this in case someone else searches in the issues for it - Chibi-Robo running from SD Gecko also has trouble loading into existing save files with emulated memcards enabled due to the same regression, and it works fine as of r1732

**Comment by osyu** [comment] 2024-09-29 19:40
Mentioning this in case someone searches in the issues for it - Chibi-Robo running from SD Gecko also has trouble loading into existing save files with emulated memcards enabled, seemingly due to the same regression, since it works fine as of r1732
