### ISSUE TITLE
Bring WiiRD Debugging Out of Conflict with Hypervisor

### ISSUE THREAD

**Issue by ReclaimerShawn** [emukidid/swiss-gc#733] opened 2022-09-18 03:16 UTC
### Describe the feature

A year ago, I created an issue on here saying that I couldn't debug Gamecube games using a USB Gekco and Swiss. That issue can be found here: https://github.com/emukidid/swiss-gc/issues/569#issue-976325663

I was told that WiiRD Debugging was in conflict with the current hypervisor. That was in v0.5r1138 and this issue is still present in v0.6r1362. Could you all possibly bring WiiRD Debugging out of conflict with the hypervisor? Thanks for reading.

**Comment by Extrems** [comment] 2022-09-18 04:39
Duplicate of issue #569.

**Closed by Extrems** 2022-09-18 04:39 UTC
Labels: duplicate
