### ISSUE TITLE
[Issue]: Activating In-Game Reset option (Reboot) causes sd card slot B to disappear

### ISSUE THREAD

**Issue by kimbapslice** [emukidid/swiss-gc#671] opened 2022-05-10 19:03 UTC
### Describe the bug

In Game Reset causes the SD card slot B to disappear until a reboot or going back to the bios screen.

### Steps to reproduce

I am on Swiss rev1318 (commit 0a1ae93) with the following config:

NTSC DOL-001
Slot A - 1019 memory card
Slot B - SD card adapter with 4GB sd card (happens with fat32/exfat)
GCLOADER - 2.0.0beta
SD/IDE Speed: 32MHz
In-Game Reset: Reboot
Config Device: GC Loader
AVE Compat: GCVideo

Start F-Zero GX for example from GCLoader and then during gameplay do an IGR. The sd card in slot B is gone. 1080 Avalanche is another. I do not think it happens on every game. Mario Sunshine reboots correctly.

### Expected behavior

Slot B sd card adapter should still be present without a reboot or going to the bios and back after IGR. Thank you for the great work on Swiss!

**Comment by kimbapslice** [comment] 2022-05-11 02:44
Thank you for the workaround, I only have GBI on the sd card so it's not a big deal. I could try moving GBI over to the GCloader as well. I wanted to report the bug either way.

**Comment by Extrems** [comment] 2022-05-14 16:55
Duplicate of issue #299.

**Closed by Extrems** 2022-05-14 16:55 UTC
Labels: duplicate
