### ISSUE TITLE
UPDATE SWISS OVER THE NETWORK

### ISSUE THREAD

**Issue by Diegorella** [emukidid/swiss-gc#862] opened 2024-03-29 20:37 UTC
### Describe the feature

seen the community's advances towards Swiss, now with cheap network functions through ETH2GC
 
the solocitation is as follows.

 create an online HOMEBREWs update function via a server.
flap/ way/
to update SWISS online via the network.

**Comment by Extrems** [comment] 2024-03-29 20:55
Duplicate of issue #332.

**Closed by Extrems** 2024-03-29 20:55 UTC
Labels: duplicate
