### ISSUE TITLE
Fixed in 220ab1e (r1355).

### ISSUE THREAD

**Issue by retrofank** [emukidid/swiss-gc#764] opened 2023-01-04 10:00 UTC
Fixed in 220ab1e (r1355).

_Originally posted by @Extrems in https://github.com/emukidid/swiss-gc/issues/497#issuecomment-1211565325_
    
Is this open again in the latest 1400 build?  
I just had a look at this and booted disc 2 of Double Agent using the latest 1400 build with a GCloader (full size redump iso). 

Started a new game and it hung on a black screen when switching to disc 1 automatically. I tried other disc 2 titles like MGS TS and that worked by auto switching to disc 1 after loading disc 2 and starting a new game.

Chaos Theory does the same behaviour when booting Disc 2 and starting a New Game (Black screen when auto switching to Disc 1)

**Comment by Diegorella** [comment] 2023-01-04 12:57
the problem is in the use of GCloader. the 2 games EXCHANGE well for the SD.

**Comment by retrofank** [comment] 2023-01-04 13:28
Oh, that sucks, if that's the case.  Can it be patched in Swiss or does GCloader need a new firmware fix?

**Comment by Extrems** [comment] 2023-01-04 15:23
The issue seem to be limited to using passive SD card adapters as patch device. Using the GC Loader is not affected (requires firmware 2.0.0 or later).

**Comment by retrofank** [comment] 2023-01-04 15:28
I see, I only just updated to 2.00 a couple of days ago.  So I need to set GCloader in Swiss as the patch device and to save the config to, instead of the SD card adapter?

**Comment by Extrems** [comment] 2023-01-04 15:35
Setting the configuration device to the GC Loader will make Swiss prefer it as your patch device.

**Comment by retrofank** [comment] 2023-01-04 17:09
Fixed as of GCL Firmware 2.00.

**Comment by Extrems** [comment] 2023-01-04 23:42
Fixed in 59218b9 (r1407).

**Closed by Extrems** 2023-01-04 23:42 UTC
Labels: bug, gc loader, device handling
