### ISSUE TITLE
IGR - black screen

### ISSUE THREAD

**Issue by ZweiBR** [emukidid/swiss-gc#515] opened 2021-04-04 01:30 UTC
rename the file swiss_r1060 to igr.dol making the sequence of buttons (B+R+Z+ ⇩) to return to the list of games presents a black screen.

**Comment by Extrems** [comment] 2021-04-04 02:01
Duplicate of issue #364.

**Closed by Extrems** 2021-04-04 02:01 UTC
Labels: duplicate

**Comment by ZweiBR** [comment] 2021-04-04 02:43
tranks
