### ISSUE TITLE
Swiss+GCLoader - Disc does not contain valid word at 0x1C

### ISSUE THREAD

**Issue by djc5166** [emukidid/swiss-gc#342] opened 2020-05-16 21:41 UTC
US gamecube
Swiss v0.5r827
GCLoader FW v1.0.0

After the GameCube is powered off for long enough (still unsure how long exactly). The first power on and boot into Swiss (boot.iso on the SD card) will show "Disc does not contain valid word at 0x1C" error when trying to load any game ISO. During this first boot, Swiss is also unable to load game banners for any games past the first page in the list file browser.

After power-cycling, everything is fine until the GameCube is powered off (again for some length of time, not exactly sure how long yet).

At first I thought it was something to do with the SD card, but I've tried multiple different ones, also its easily reproducible on my GameCube.

Not sure if this is actually a Swiss or GCLoader issue (or something else entirely?)

![3Ic28Bzv](https://user-images.githubusercontent.com/19207074/82130697-c475c900-979b-11ea-917d-197198b22a0f.jpg)
![WBrRsgA4](https://user-images.githubusercontent.com/19207074/82130698-c475c900-979b-11ea-8dd6-0addc6d671c3.jpg)

**Comment by Extrems** [comment] 2020-05-16 22:24
I don't think this is our fault.

**Comment by hurda** [comment] 2020-05-17 13:44
r827 was released in April, yet your screenshots show March. Is your GC's clock-battery dead? Maybe that has some side-effects.

**Comment by djc5166** [comment] 2020-05-17 17:15
It's definitely dead, maybe it get confused if the files are from the future?

**Comment by shiggypoo** [comment] 2020-06-08 14:17
I am having this exact same problem under these exact same circumstances with Swiss on my GC Loader I received last week. It only seems to be after the GameCube is powered off for a short amount of time, and once I power cycle it everything in Swiss loads normally again with no apparent game play issues until I turn it off and let it rest for more than 10 minutes.

- I am running the latest Swiss r836.

- Brand new Energizer CR2032 battery installed when I installed the GC Loader last week, and I have just confirmed that the time and date are in fact current.

- SD Card is a brand new Sandisk Ultra 200GB MicroSD + SD Adapter.

- SD Card is formatted as FAT32 / 32k cluster size.

- I'm using a Laser Bear 3D printed GC Loader mount that utilizes an SD card ribbon cable to the GC Loader.

- The system is a DOL-001 / IPL 1.1 from Japan that has a region switch installed (region switched to USA and using USA Swiss ISO)

- I've tried renaming several game ISOs to boot.iso and the GC Loader loads them and plays them perfectly, so I'm starting to think that this must be a glitch with Swiss if others are encountering it.

@djc5166 how does your set up compare, and a month later are you still having these issues?

**Comment by djc5166** [comment] 2020-06-08 14:40
My console is the USA version, using Sandisk Ultra(80) 32 and 64GB cards. Otherwise the setup is the same, my clock battery is replaced now.

**Comment by shiggypoo** [comment] 2020-06-11 11:27
I updated my GC Loader to v1.0.1 two days ago and have not experienced the issue since.

**Comment by travazz** [comment] 2020-08-30 22:45
I have the exact same problem as stated above.

**Comment by BarcodeGG** [comment] 2020-08-31 03:32
I have the same problem. I have a Japanese and US Gamecube with GC Loader installed on both. Updated to firmware 1.1.0 using latest version of Swiss v0.5 r888 and 200gb Sandisk Micro SD cards.

**Comment by travazz** [comment] 2020-08-31 14:57
When you guys are resetting the device, do all the games start up? I don’t get any change on power cycling.

**Comment by BarcodeGG** [comment] 2020-09-01 02:33
I was able to fix the problem by formating the micro sd card to exFAT through Windows 10. Do not use the Ridgecorp GUI Format FAT32 tool

**Comment by Extrems** [comment] 2020-10-05 03:41
Can you try without the SD extension cable?

**Comment by Simon-Belmont** [comment] 2020-11-18 00:18
Greetings. I recently bought a GC Loader PNP and it works great but unfortunately I ran into the the same issue. Some backups (images) do not load nor show up (banners) in the Swiss menu and I get the same "Disc does not contain valid word at 0x1c" message. I've noticed that after I copy more than 25-30 backups (isos) to the sd card, it does that. If I don't exceed that limit, the isos do show up and load. I'm currently on Swiss version r927, using a FAT32 128gb micro sd card, with the latest GC Loader firmware 1.1.2. installed. I've tried disconnecting the GC Loader and reconnecting it. I've tried several versions of Swiss. I've tried GC Loader firmware 1.1.0. I've tried power cycling the console. I've tried formatting the sd card to exFAT. I don't know what else to do. Can someone please help?

**Comment by djc5166** [comment] 2020-11-20 20:21
I haven't really checked mine in awhile but it seemed resolved last time I looked at it. I had also replaced the RTC battery, but I'm still not sure if that has anything to do with this issue.

I'm moving all my stuff around right now, but I will check soon with the latest swiss and GCloader FW.

**Comment by beardylee** [comment] 2021-07-20 23:46
Just purchased a GC Loader from the new stock and am having this issue. Running Swiss v0.5 with GC Loader 1.1.2. Using a SanDisk Ultra 256 SD card (have also tried a PNY 256 card with no success), formatted in FAT32 via Mac Disk Utility. 

With the card full, only a handful of games showed banners and would load. Most of my games are Nkit, but the few that seemed to work were just ISO. Also, I was unable to flash the GC Loader firmware update on my card that was full. I had to put the .dol file onto an empty card with only it and Swiss in order to get the GC Loader to update. 

I put one Nkit game onto the PNY card, and it loaded no problem. Maybe the key is what Simon-Belmont mentioned above--only loading 25-20 games on the card?

Power cycling does nothing for me, unfortunately. The same handful of games remain the same, no matter the power cycling or time off or on.

**Closed** 2022-03-03 21:11 UTC
Labels: invalid
